language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -e .
# command to run tests
script:
  # cd so we test the install, not the repo
  - cd `mktemp -d`
  - pytest

